name: Publish

on:
  push:
    branches:
      - main
      - master

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore(release)')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Git config
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: "@prevayl"
          always-auth: true

      - name: Restore npm cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: yarn install --frozen-lockfile
        env:
          GH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}

      - name: Version package
        run: npx standard-version --no-verify
        env:
          GH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}

      - name: Publish package
        run: yarn publish
        env:
          GH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}

      - name: Publish package tag
        id: publish_tag
        run: |
          git push --follow-tags
          echo ::set-output name=tag_name::$(git describe HEAD --abbrev=0)

      - name: Create package release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: ${{ steps.publish_tag.outputs.tag_name }}
          tag_name: ${{ steps.publish_tag.outputs.tag_name }}
          body: 'react-native-zoomable-view'
